#!/bin/bash

# ═══════════════════════════════════════════════════════════════════
# CLOUD DISTRIBUÉ - GUIDE DE DÉMARRAGE RAPIDE
# ═══════════════════════════════════════════════════════════════════

clear

cat << "EOF"
╔═══════════════════════════════════════════════════════════════════╗
║                    CLOUD DISTRIBUÉ                               ║
║              Stockage Résilient en Réseau                        ║
╚═══════════════════════════════════════════════════════════════════╝

EOF

echo "📋 CONFIGURATION DU SYSTÈME:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  Serveur:            http://10.134.17.222:8080"
echo "  Port HTTP:          8080"
echo ""
echo "  Architecture:"
echo "    • DIR Server      (port 7000) - Métadonnées"
echo "    • OSD x4          (ports 9001-9004) - Stockage"
echo "    • HTTP API        (port 8080) - Accès réseau"
echo ""
echo "  Réplication:        3x (survit à 2 pannes simultanées)"
echo "  Chunk size:         1 MB"
echo ""

echo ""
echo "🚀 DÉMARRER LE SERVEUR:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  Depuis le terminal du serveur:"
echo ""
echo "    $ cd Data-Stockage-main"
echo "    $ ./run.sh"
echo ""
echo "  Le serveur démarre en ~5 secondes"
echo ""

echo ""
echo "💻 SE CONNECTER DEPUIS UN AUTRE ORDINATEUR:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  1️⃣  INTERFACE WEB (Le plus simple!)"
echo "  ────────────────────────────────────────"
echo ""
echo "    Ouvrir Firefox ou Chrome:"
echo ""
echo "      → http://10.134.17.222:8080"
echo ""
echo "    Vous verrez:"
echo "      • Accueil avec liens"
echo "      • /ui → Interface web complète (upload/download)"
echo ""
echo ""

echo "  2️⃣  CLIENT AUTONOME TÉLÉCHARGEABLE"
echo "  ────────────────────────────────────────"
echo ""
echo "    Copier le fichier client-standalone.html"
echo "    Ouvrir dans un navigateur"
echo "    L'adresse IP peut être modifiée dans le menu"
echo ""
echo ""

echo "  3️⃣  API REST DIRECTE"
echo "  ────────────────────────────────────────"
echo ""
echo "    Upload:"
echo "      $ curl -X POST --data-binary @fichier.pdf \\"
echo "        'http://10.134.17.222:8080/api/upload?fileName=fichier.pdf&userId=user1'"
echo ""
echo "    Download:"
echo "      $ curl 'http://10.134.17.222:8080/api/download?fileName=fichier.pdf' -O"
echo ""
echo "    Lister fichiers:"
echo "      $ curl 'http://10.134.17.222:8080/api/files' | python3 -m json.tool"
echo ""
echo ""

echo ""
echo "📚 DOCUMENTATION:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  • GUIDE_CONNEXION.md    - Guide complet pour se connecter"
echo "  • client-example.js     - Classe JavaScript réutilisable"
echo "  • client-standalone.html - Client web autonome"
echo "  • README.md             - Documentation complète"
echo "  • API_REST.md           - Spécification API (si créé)"
echo ""
echo ""

echo ""
echo "🔍 VÉRIFIER QUE ÇA FONCTIONNE:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  Depuis un autre ordinateur du réseau:"
echo ""
echo "    $ curl -I 'http://10.134.17.222:8080/api/files'"
echo ""
echo "  Doit retourner: HTTP/1.1 200 OK"
echo ""
echo ""

echo ""
echo "⚠️  POINTS IMPORTANTS:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  ☑ Tous les ordinateurs doivent être sur le MÊME RÉSEAU"
echo "  ☑ L'adresse IP 10.134.17.222 peut être différente"
echo "    Vérifier avec: hostname -I  (sur Linux) ou ipconfig (Windows)"
echo "  ☑ Le port 8080 ne doit pas être bloqué par un firewall"
echo "  ☑ Les fichiers sont partagés entre tous les clients"
echo "  ☑ Aucune authentification (userId est juste un identifiant)"
echo ""
echo ""

echo ""
echo "🎯 PROCHAINES ÉTAPES:"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "  1. Lancer le serveur: ./run.sh"
echo "  2. Ouvrir navigateur: http://10.134.17.222:8080"
echo "  3. Uploader un fichier via l'interface"
echo "  4. Voir le fichier listewith automatiquement"
echo "  5. Tester depuis un autre ordinateur"
echo ""
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "Besoin d'aide? Lire GUIDE_CONNEXION.md"
echo "════════════════════════════════════════════════════════════════"
echo ""
